### ISSUE TITLE
Issue with referring to Mixpanel on WebGL Build

### ISSUE THREAD

**Issue by SamLucyk** [rocktavious/mixpanel-unity#2]
Refer to https://github.com/mixpanel/mixpanel-unity/issues/10 for the orignal details - Will post more progress here.

**Comment by SamLucyk** [comment]
in Mixpanel.js I added this. I relized Identify was working but it was failing on track. I see now that SuperProperties is what is creating the error. Again not sure why but it wouldn't get past Debug.Log("4")

 internal static void track(string eventName, Value properties)
        {
            Debug.Log("1");
            if (!IsTracking) return;
            Debug.Log("2");
            foreach (var item in OnceProperties)
            {
                Debug.Log("2" + item.Key);
                properties[item.Key] =  item.Value;
            }
            Debug.Log("3");
            OnceProperties = new Value();
            Debug.Log("4");
            Debug.Log("SuperProps" + SuperProperties.Count);
            foreach (var item in SuperProperties)
            {
                Debug.Log("4a" + item.Key);
                properties[item.Key] = item.Value;
                Debug.Log("4b" + item.Key);
           }
}

**Comment by rocktavious** [comment]
@SamLucyk so its failing on `foreach (var item in SuperProperties)` or its failing on `OnceProperties = new Value();` ?

I'll run a few more tests setting SuperProperties and OnceProperties and stuff and respond back.  I might build in a demo scene and have you try the same thing as me.  Just to rule out differences in our setups.

**Comment by SamLucyk** [comment]
Failing on referring to SuperProperties - I'll get back to debugging in the
morning but still not sure why - I'm wondering if its cache related some
how but not sure where to look. Just gonna see if I can get through the
rest of the function without Super Properties and see where it gets.

I'll keep you updated - but won't be able to try anything till the morning.

**Comment by rocktavious** [comment]
@SamLucyk So here is the script i'm using to test with
```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using mixpanel;

public class MixpanelTester : MonoBehaviour
{
    public Text id;

    public void Update()
    {
        id.text = Mixpanel.DistinctID;
    }

    public void Test1()
    {
        Mixpanel.Track("APITESTING");
    }

    public void Test2()
    {
        Mixpanel.Identify("Mixpanel Tester");
    }

    public void Test3()
    {
        Mixpanel.Alias("MPTest");
    }

    public void Test4()
    {
        Mixpanel.RegisterOnce("TimeOfDay", "Morning");
    }

    public void Test5()
    {
        Mixpanel.Register("TimeOfDay2", "Night");
    }

    public void Test6()
    {
        var data = new Value();
        data["Data"] = "Hello World";
        Mixpanel.Track("APITESTING", data);
    }
}
```

All of this works in my WebGL build (both as debug and as not debug)
and here are the events in mixpanel

![MixpanelTest](https://user-images.githubusercontent.com/735015/55925579-8c34ac00-5bd3-11e9-8a5d-1c033d5a3407.png)

I pushed changes to this repo tonight that fix the Register bugs as well as the distinct id bugs (and a few others i found by looking for similar mistakes).  The above tests were run with these latest changes.

**Comment by SamLucyk** [comment]
Hey @rocktavious confirmed that the error is coming from `JsonConvert.SerializeObject(new Value())` trying to dig in and see why but thats where it throws the error when ever that happens. Specifically was seeing it in the get methods for SuperProperties and TimedEvents. I'll keep digging but if you want to just confirm that your build has no problem even writing 'Debug.Log(JsonConvert.SerializeObject(new Value())' then that would help. I feel your example code would hit that at some point but just not sure why it's happening yet for me

**Comment by SamLucyk** [comment]
https://github.com/SaladLab/Json.Net.Unity3D I think this answers it - trying it out now but in the first FAQ they refer to the issue I'm having.

**Comment by rocktavious** [comment]
@SamLucyk Oh nice i did not know the standard Newtonsoft wasn't compatible with Unity - i'll dig into converting over to the Unity compatible one - because yes it does look like the issue you're having is one of the things that version fixes.  Great find!

**Comment by SamLucyk** [comment]
Finally working!

So ended up removing the Newtonsoft.json files that are in this repo and instead installing this https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

Still going to test on IOS and Android but should be good to go with this going forward :) Still not sure why it works on a empty project and not the one I'm working on but glad this solved it. Thanks a lot for your help @rocktavious I'll write back with any more information I get.

**Comment by rocktavious** [comment]
@SamLucyk great!  I'll look into either SaladLab or that unity package and see which one is using the more recent version of Newtonsoft and replace the one in this package with it.

it is very strange it works in a fresh project - but 🤷‍♂️ 

Let me know if you run into any more bugs or create issues here - bugs you encounter also help me "not" encounter them in my usages ;) . FWIW i've reached out to mixpanel support to see about opening up a discussion with them about getting all this merged back upstream so their real library acts better!

**Comment by SamLucyk** [comment]
That would be awesome! Let me know how the conversation goes with them. 

Just submitted another issue about the Mixpanel Properties included in events - probably would take a good amount of time to rewrite all of that so getting it merged back upstream might help with that :)
